source 'https://rubygems.org'

gemspec

group :test do
  gem 'cucumber',     '~> 1.3'
  gem 'aruba',        '~> 0.6'
  gem 'rspec',        '~> 3.2'
  gem 'simplecov',    '~> 0.9'
  gem 'factory_girl', '~> 4.5'
end

group :development do
  gem 'rake',      '~> 10.4'
  gem 'yard',      '~> 0.8', :require => false
  gem 'redcarpet', '~> 3.2', platforms: :mri
end
