source "https://rubygems.org"


gem "rails", "4.1.1"
gem "sqlite3"
gem "sass-rails", "~> 4.0.3"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.0.0"
gem "jquery-rails"
gem "bootstrap-sass", "~> 3.2.0"
gem 'jquery-tablesorter', '~> 1.14.1'

gem "sdoc", "~> 0.4.0",          group: :doc

group :test, :development do
  gem "spring"
  gem "rspec-rails"
  gem 'factory_girl_rails', '~> 4.5.0'
  gem "capybara"
  gem "database_cleaner", git: "git@github.com:bmabey/database_cleaner.git"
  gem "ruby_css_lint"
  gem "selenium-webdriver"

  gem 'timecop', '~> 0.7.1'
  gem 'faker', '~> 1.4.3'
end
