# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks

task :check_for_local_changes do
  changed_files = `git status --porcelain`.split("\n")
  abort "You have local changes:\n#{changed_files.join("\n")}" unless changed_files.empty?
end

desc 'package up everything into a .zip to send to a candidate'
task :package => :check_for_local_changes do
  chdir("..") do
    command = "zip -x take-home-challenge-next-level/tmp/cache/\\* -x take-home-challenge-next-level/.git/\\* -x take-home-challenge-next-level/RUBRIC.md -r take-home-challenge.zip take-home-challenge-next-level/*"
    sh command do |ok,res|
      raise "Problem running #{command}" unless ok
    end
  end 
end

desc 'package up everything into a .zip to return to Stitch Fix'
task :repackage => :check_for_local_changes do
  dirname = File.basename(Dir.getwd)
  puts "Zipping #{dirname}..."
  chdir("..") do
    command = "zip -x #{dirname}/tmp/cache/\\* -r #{dirname}.zip #{dirname}"
    sh command do |ok,res|
      raise "Problem running #{command}" unless ok
    end
  end 
end

desc 'reset and re-seed the SQLite databases'
task 'db:clobber' do
  sh 'rm -f db/*.sqlite3'
  Rake::Task['db:migrate'].invoke
  Rake::Task['db:seed'].invoke
end
